### ISSUE TITLE
installing in lazarus fails

### ISSUE THREAD

**Issue by EllenLouiseRipley** [pragmaticlinuxblog/cancomm_lazarus#1]
Raspbian 10
FPC Version 3.2.2
Lazarus 2.2.0
I installed the cancomm package as described on the man without issues.
Linking Lazarus after installing the package shows the following messages:
IDE erstellen: Exit code 2, Fehler: 2, Warnungen: 2
Warning: svn not in path.
Warning: linker: /usr/bin/ld: -lcancomm kann nicht gefunden werden
make[2]: *** [Makefile:4667: lazarus] Fehler 1
make[1]: *** [Makefile:5105: idepkg] Fehler 2
Error: make: *** [Makefile:3739: idepkg] Fehler 2
lazarus.pp(167,1) Error: Error while linking

**Comment by pragmaticlinuxblog** [comment]
Hi,

This has an easy fix. You just need to install the LibCanComm shared library on your Raspberry PI. You can find more info regarding this in the user manual: https://pragmaticlinuxblog.github.io/cancomm_lazarus/#requirements.

**Comment by EllenLouiseRipley** [comment]
Hi, thanks for the reply. I did install the lib. 
I will take some screenshots and provide them. 
Best regards 

Thomas 

Von meinem iPhone gesendet
